FROM kaldiasr/kaldi

# Sistem paketleri
RUN apt-get update && apt-get install -y \
    sox \
    libsox-fmt-all \
    python3-pip \
    espeak-ng \
    && rm -rf /var/lib/apt/lists/*

# Python paketleri
RUN pip install phonemizer --break-system-packages

# Varsayılan çalışma dizini
WORKDIR /opt/kaldi/egs/commonvoice/s5

ENTRYPOINT ["bash", "/data/proje/docker_baslat.sh"]
